server {
    listen 80;
    server_name _;
    
    # Add these lines at server level
    absolute_redirect off;
    server_name_in_redirect off;

    # Add specific location for /projects
    location = /projects {
        root /app/frontend/build;
        try_files /index.html =404;
    }

    location / {
        root /app/frontend/build;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        rewrite ^/api/(.*) /$1 break;
        proxy_pass http://localhost:2840;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
