events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        listen 443 ssl;
        server_name jimchen.me www.jimchen.me;

        ssl_certificate /etc/letsencrypt/live/jimchen.me/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/jimchen.me/privkey.pem;

        if ($scheme = http) {
            return 301 https://$server_name$request_uri;
        }

        root /root/My-Website/frontend/build;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        location /api/ {
            rewrite ^/api/(.*) /$1 break;
            proxy_pass http://localhost:2840;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
